### ISSUE TITLE
mongodb uri with mustache style

### ISSUE THREAD

**Issue by rafael-pinho** [ozomer/node-red-contrib-mongodb2#10]
Hi there,

When I configure mongodb server uri, I need to put the uri as a string, like 'mongodb://localhost:27017'. But in my case, this uri will stay in a environment variable. In my settings.js I put the process.env values in the global context, then in a function box I get the environment variable value in the global context like this:

``` javascript
msg.mongoUri = context.global.env.MONGO_URI
```

So, is there a way to pass msg.mongoUri value to mongodb box uri field? If not, can I send you a pull request to make this possible using mustache style? It would be like this:

![image](https://cloud.githubusercontent.com/assets/5205896/23301045/08b5a2e6-fa67-11e6-80a1-8649f25045f9.png)

Best regards

Rafael

And by the way...sorry for my bad english skills.

**Comment by ozomer** [comment]
Hi,
This is a general problem discussed [here](https://groups.google.com/forum/#!searchin/node-red/from$3Ame$20mongodb%7Csort:relevance/node-red/qTlYWKF-Nrw/AvVdMrl0AwAJ).
Solving it for strings is not won't be enough, what about numerical values? checkboxes?

In my place we solved this issue by replacing the [storage module](http://nodered.org/docs/api/storage) that is used to store the flows (and their changes). There are few examples for implementing storage module [here](https://github.com/node-red/node-red/blob/master/red/runtime/storage/localfilesystem.js) and [here](https://github.com/ibmets/node-red-bluemix/tree/master/public/app).

We are using mongodb to store the flows, in a code similar to [this](https://gist.github.com/ozomer/8ac5d1c30b4f0a1e1831).
Notice the `preprocess` function. It is called for each node configuration and loops on the values. Whenever the value is an object with `type: "config"`, it runs a vm on `key` (with `process.env` for its context). For example, if the object is: `{"type": "config", "key": "MONGO_URI"}` it will be replaced with your `MONGO_URI` environment variable.

Now all you have to do is to save the flows with a mongo uri of: "BLABLABLA", shutdown node-red, manually change the "BLABLABLA" value in your db (or local-storage) with `{"type": "config", "key": "MONGO_URI"}` and restart node-red.

You can also use this trick for numerical values, and write short code in `key`, like: `{"type": "config", "key": "(MY_ENV_VAR * 1) || 0"}`.

Regards,
Oren

P.S.
Notice also that the `saveFlows` function does not simply overrides the configuration. It checks if the value actually changed, and otherwise keeps the old value. So if you change a different field in the configuration, the old field, which is saved as `{"type": "config", "key", "..."}`, will remain as-is.

**Comment by rafael-pinho** [comment]
Hi Oren.

I understand and I'm going to implement a storage module to solve my problem too. I found the same issue in "other boxes" and I think this solution will solve them all. I will share my implementation when I finish it.

Best regards,
Rafael

**Comment by rslangham** [comment]
I was able to get this to work using env variables in the format of $(VARIABLE) in the mongodb2 server config for the URI,  user, and password.   In research of this,  I found where it was stated the env value reference will work for almost any Node-Red node config text entry.   I placed the env format content in each of the fields and verified that it accessed and used environment variables that I had defined,  e.g.   $(MONGODB_USER).  $(MONGODB_URI), ...  

I did find one minor bug with this.  When you close the mongodb server and config dialogs and deploy, then go back and re-open them again, the user text field will contain the value (e.g. bobjones) of the environment user specified.  I did some additional tests to see if the underlying reference was still there.   I changed the env user variable value in the system and mongodb access failed.   Changed it back to the correct value and it worked.   So, appears to be just a display issue in the config dialog.  Though, pretty sure if I had modified something else in the config dialog and saved it, that it would lose my  $(env) reference.  So, just have to remember to re-input the user env field if ever modify anything in the config dialog.
