### ISSUE TITLE
http response from mongodb2 node not working

### ISSUE THREAD

**Issue by geoalexidis** [ozomer/node-red-contrib-mongodb2#6]

**Comment by ozomer** [comment]
I assume that you closed the issue because you found a solution - right?

**Comment by geoalexidis** [comment]
Yes thats right. Is there a way to delete it?
The problem was me doing something minor different...

Von meinem Windows Phone gesendet

---

Von: Oren Zomermailto:notifications@github.com
Gesendet: ‎14.‎05.‎2016 11:56
An: ozomer/node-red-contrib-mongodb2mailto:node-red-contrib-mongodb2@noreply.github.com
Cc: guitar-heromailto:geo-me@hotmail.com; State changemailto:state_change@noreply.github.com
Betreff: Re: [ozomer/node-red-contrib-mongodb2] http response from mongodb2 node not working (#6)

I assume that you closed the issue because you found a solution - right?

On 14 May 2016 at 12:54, guitar-hero notifications@github.com wrote:

> Closed #6 https://github.com/ozomer/node-red-contrib-mongodb2/issues/6.
> 
> —
> You are receiving this because you are subscribed to this thread.
> Reply to this email directly or view it on GitHub
> https://github.com/ozomer/node-red-contrib-mongodb2/issues/6#event-660678433

---

**Comment by ozomer** [comment]
I don't know if you can delete it. Don't worry, closing the issue is fine.
On May 14, 2016 1:05 PM, "guitar-hero" notifications@github.com wrote:

Yes thats right. Is there a way to delete it?
The problem was me doing something minor different...

Von meinem Windows Phone gesendet

---

Von: Oren Zomermailto:notifications@github.com
Gesendet: ‎14.‎05.‎2016 11:56
An: ozomer/node-red-contrib-mongodb2<mailto:
node-red-contrib-mongodb2@noreply.github.com>
Cc: guitar-heromailto:geo-me@hotmail.com; State change<mailto:
state_change@noreply.github.com>
Betreff: Re: [ozomer/node-red-contrib-mongodb2] http response from mongodb2
node not working (#6)

I assume that you closed the issue because you found a solution - right?

On 14 May 2016 at 12:54, guitar-hero notifications@github.com wrote:

> Closed #6 https://github.com/ozomer/node-red-contrib-mongodb2/issues/6.
> 
> —
> You are receiving this because you are subscribed to this thread.
> Reply to this email directly or view it on GitHub
> <
> https://github.com/ozomer/node-red-contrib-mongodb2/issues/6#event-660678433

---
